site_name: XJU Algorithm Wiki
theme:
    name: material
    features:
        - navigation.tabs  # 顶部横栏
        - navigation.sections   # 二级导航展开
        - navigation.expand     # 自动展开侧边栏
        - navigation.top
        - content.code.copy # Code Block Copy Button
    hide:
        - toc                   # 取消右侧目录
    # ------ Dark and Light Mode ------
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference
    # ------ Dark and Light Mode ------
repo_url: https://github.com/winbeau/mkdocs-wiki
markdown_extensions:
    - pymdownx.highlight: # Code Block
        linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite # Code Block
    - pymdownx.snippets # Code Block
    - pymdownx.superfences: # Mermaid
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex: # KaTeX
        generic: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css

nav:
  - 首页: index.md
  - 比赛存档:
      - 博达校区新生赛[2025-09-27]:
          - Problem A: contests/2025Sep27/pA.md
          - Problem B: contests/2025Sep27/pB.md
          - Problem C: contests/2025Sep27/pC.md
          - Problem D: contests/2025Sep27/pD.md
          - Problem E: contests/2025Sep27/pE.md
          - Problem F: contests/2025Sep27/pF.md
          - Problem G: contests/2025Sep27/pG.md
          - Problem H: contests/2025Sep27/pH.md
          - Problem I: contests/2025Sep27/pI.md
          - Problem J: contests/2025Sep27/pJ.md
          - Problem K: contests/2025Sep27/pK.md
  - 按知识点索引:
      - 分治
  - 模板 / 常用代码:
      - ST表
  - 关于: about.md
